### ISSUE TITLE
hi unluckynelson have a query

### ISSUE THREAD

**Issue by worldfellow** [unluckynelson/quasar-apollo-test#1]
just wanted to know whats the update on this repo i am unable to find it https://github.com/unluckynelson/pdfmake-generator

**Comment by unluckynelson** [comment]
Hi @worldfellow this was a private repo, I haven't touched it in 5 years, I'm curious how you heard about it, I made it public now so you can access it

**Comment by worldfellow** [comment]
Wow thanks so much now i have a head start in making a dynamic dd in pdfmake

> Hi @worldfellow this was a private repo, I haven't touched it in 5 years, I'm curious how you heard about it, I made it public now so you can access it
